### ISSUE TITLE
Broken link to guide for gear developers

### ISSUE THREAD

**Issue by fire** [access-company/antikythera#72]
https://hexdocs.pm/antikythera/gear_developers/ on https://hexdocs.pm/antikythera/getting_started.html

**Comment by aMasakiTakahashi** [comment]
Thank you for your comment.

I fixed it.
The hexdoc will be modified on the next version.

**Comment by fire** [comment]
https://hexdocs.pm/antikythera/gear_developers/ Is still broken.

**Comment by ttokit** [comment]
Thank you for letting us know.
We have released a new version (v0.3.0) and confirmed that the problem has been resolved.

Now the link has been changed to https://hexdocs.pm/antikythera/gear_developers.html.
Please click directly or via the ["Getting Started"](https://hexdocs.pm/antikythera/getting_started.html) page.
